### PR TITLE
Some opt

### PR DESCRIPTION
**Pull request by M3351AN**
1. Add .gitignore
~~2. Add game module chk before init~~(del due to manual mapping error sometimes)
3. Port vector header from liv's OS-Imgui lib
4. Fix debug build error
5. Basic ingame radar
6. Fix radar function typo
7. Port overlay radar from Aimstar(might buggy)
8. Bypass OBS

### CODE REVIEW

**Comment by M3351AN** [comment]
overlay radar ported, still stuffs could be improve

**Comment by M3351AN** [comment]
bebc8eaf4cb9159e39ce39fc0e3dc0a0
Bypass OBS can be working with game capture rn

**Comment by MitilcC** [comment]
my computer has some problems，so I can't work these days

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MitilcC** [comment]
wait~ I am writing codes T . T

**Comment by MitilcC** [comment]
thanks

**Pull request closed without merging**
